---
- hosts: all
  become: true
  gather_facts: true

  tasks:
   - name: install httpd
     yum: name=httpd state=latest update_cache=yes
   - name: start httpd
     service: name=httpd state=started
   - name: open port for service
     firewalld: service={{item.name}} permanent={{item.permanent}} state={{item.state}}
     with_items:
         - {name: 'http' , permanent: true, state: 'enabled'}
         - {name: 'https', permanent: true, state: 'enabled'}
         - {name: 'ftp', permanent: true, state: 'enabled'}
   - name: firewalld restart
     service: name=firewalld state=restarted


- hosts: webservice
  become: true
  gather_facts: true
  serial: 1

  tasks:
   - name: hello web01
     debug: msg="hello web01"

- hosts: lb
  become: true
  gather_facts: true
  serial: 1

  tasks:
   - name: update apt cache
     debug: msg="hello lb"
